
package Pages.Add;

import AppFunctionality.Careers;
import AppFunctionality.Careers2Courses;
import AppFunctionality.Courses;
import java.sql.ResultSet;

/**
 *
 * @author Kevin Ewald
 */
public class AddCareer2Course extends javax.swing.JFrame {

    Courses courses;
    Careers careers;
    Careers2Courses c2c;
    
    ResultSet coursesRS;
    ResultSet careersRS;
    /**
     * Creates new form AddCareer2Course
     */
    public AddCareer2Course() {
        initComponents();
        labelCareerOutcome.setEnabled(false);
        comboCareerOutcome.setEnabled(false);
        labelError.setVisible(false);
        btnLink.setEnabled(false);
        labelLinkSuccess.setVisible(false);
        
        comboCareerOutcome.removeAllItems();
        comboCareerOutcome.addItem("- Select -");
        
        comboCourse.removeAllItems();
        comboCourse.addItem("- Select -");
        
        try
        {
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourse.addItem(courseName);
            }
        }
        catch(Exception ex)
        {
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCourse = new javax.swing.JLabel();
        comboCourse = new javax.swing.JComboBox();
        labelCareerOutcome = new javax.swing.JLabel();
        comboCareerOutcome = new javax.swing.JComboBox();
        labelError = new javax.swing.JLabel();
        btnLink = new javax.swing.JButton();
        labelLinkSuccess = new javax.swing.JLabel();
        btnRefreshList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Link Career Outcome to Course");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Link Career to Course");

        labelCourse.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCourse.setForeground(new java.awt.Color(255, 255, 255));
        labelCourse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCourse.setText("Course:");

        comboCourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseActionPerformed(evt);
            }
        });

        labelCareerOutcome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelCareerOutcome.setForeground(new java.awt.Color(255, 255, 255));
        labelCareerOutcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCareerOutcome.setText("Career Outcome:");

        comboCareerOutcome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCareerOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCareerOutcomeActionPerformed(evt);
            }
        });

        labelError.setForeground(new java.awt.Color(204, 0, 0));
        labelError.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelError.setText("error message");

        btnLink.setText("Link");
        btnLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkActionPerformed(evt);
            }
        });

        labelLinkSuccess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelLinkSuccess.setForeground(new java.awt.Color(255, 255, 255));
        labelLinkSuccess.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelLinkSuccess.setText("jLabel2");

        btnRefreshList.setText("Refresh List");
        btnRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCareerOutcome)
                            .addComponent(labelCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCourse, 0, 247, Short.MAX_VALUE)
                            .addComponent(comboCareerOutcome, 0, 252, Short.MAX_VALUE)
                            .addComponent(labelError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLink, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshList)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLinkSuccess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboCareerOutcome, comboCourse});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourse)
                    .addComponent(comboCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshList))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCareerOutcome)
                    .addComponent(comboCareerOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLink)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLinkSuccess)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboCareerOutcome, comboCourse});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseActionPerformed
        // TODO add your handling code here:
        int index = comboCourse.getSelectedIndex();
        comboCareerOutcome.removeAllItems();
        comboCareerOutcome.addItem("- Select -");
        try
        {
            if (index > 0)
            {
                String courseChosen = (String) comboCourse.getSelectedItem();
                int disciplineID = courses.getDisciplineIDByCourseName(courseChosen);
                careers = new Careers();
                careersRS = careers.listCareers(disciplineID);
                while(careersRS.next())
                {
                    String careerName = careersRS.getString("careerName");
                    comboCareerOutcome.addItem(careerName);
                }
            comboCareerOutcome.setEnabled(true);
            labelCareerOutcome.setEnabled(true);
            }
            else
            {
                labelCareerOutcome.setEnabled(false);
                comboCareerOutcome.setEnabled(false);
                btnLink.setEnabled(false);
                labelError.setVisible(false);
            }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_comboCourseActionPerformed

    private void comboCareerOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCareerOutcomeActionPerformed
        // TODO add your handling code here:
        String courseChosen = (String) comboCourse.getSelectedItem();
        String careerChosen = (String) comboCareerOutcome.getSelectedItem();
        int index = comboCareerOutcome.getSelectedIndex();
        try
        {
            c2c = new Careers2Courses();
            if(c2c.checkIfLinkExists(courseChosen, careerChosen))
            {
                labelError.setText("This career is already linked to this course");
                labelError.setVisible(true);
                btnLink.setEnabled(false);
            }
            else if (index > 0)
            {
                btnLink.setEnabled(true);
                labelError.setVisible(false);
            }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_comboCareerOutcomeActionPerformed

    private void btnLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkActionPerformed
        // TODO add your handling code here:
        String courseChosen = (String) comboCourse.getSelectedItem();
        String careerChosen = (String) comboCareerOutcome.getSelectedItem();
        try
        {
        c2c = new Careers2Courses();
        c2c.linkCareer2Course(courseChosen, careerChosen);
        labelLinkSuccess.setText(careerChosen + " is now a possible job outcome of " + courseChosen);
        labelLinkSuccess.setVisible(true);
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnLinkActionPerformed

    private void btnRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshListActionPerformed
        // TODO add your handling code here:
        comboCourse.removeAllItems();
        comboCourse.addItem("- Select -");
        try
        {
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourse.addItem(courseName);
            }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnRefreshListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCareer2Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCareer2Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCareer2Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCareer2Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCareer2Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLink;
    private javax.swing.JButton btnRefreshList;
    private javax.swing.JComboBox comboCareerOutcome;
    public javax.swing.JComboBox comboCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCareerOutcome;
    private javax.swing.JLabel labelCourse;
    private javax.swing.JLabel labelError;
    public javax.swing.JLabel labelLinkSuccess;
    // End of variables declaration//GEN-END:variables
}
