
package Pages.Add;

import Admin.ManageIndustries;
import AppFunctionality.Industries;

/**
 *
 * @author Kevin Ewald
 */
public class AddIndustry extends javax.swing.JFrame {
    ManageIndustries manageIndustries;
    Industries industries;

    /**
     * Creates new form AddIndustry
     */
    public AddIndustry() {
        initComponents();
        labelMessage.setText("");
        btnRetry.setVisible(false);
        labelConnectionError.setVisible(false);
        labelValidationMessage.setVisible(false);
        btnAddIndustry.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTitleText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtIndustryName = new javax.swing.JTextField();
        btnAddIndustry = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        labelConnectionError = new javax.swing.JLabel();
        btnRetry = new javax.swing.JButton();
        labelValidationMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Industry");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        labelTitleText.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelTitleText.setForeground(new java.awt.Color(255, 255, 255));
        labelTitleText.setText("Add new industry:");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Industry Name:");

        txtIndustryName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIndustryNameKeyReleased(evt);
            }
        });

        btnAddIndustry.setBackground(new java.awt.Color(255, 255, 255));
        btnAddIndustry.setText("Add");
        btnAddIndustry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddIndustry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIndustryActionPerformed(evt);
            }
        });

        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("This label  is not displayed by default");

        labelConnectionError.setForeground(new java.awt.Color(255, 255, 255));
        labelConnectionError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConnectionError.setText("Error: Unable to connect to database, please check you connection");

        btnRetry.setText("Retry");
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });

        labelValidationMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelValidationMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelValidationMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelValidationMessage.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAddIndustry)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelValidationMessage))
                                    .addComponent(txtIndustryName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelConnectionError)
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRetry, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIndustryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddIndustry)
                    .addComponent(labelValidationMessage))
                .addGap(27, 27, 27)
                .addComponent(labelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelConnectionError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRetry)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIndustryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIndustryActionPerformed
        // TODO add your handling code here:
        try
        {
            manageIndustries = new ManageIndustries();
            String industryName = txtIndustryName.getText();
            
            manageIndustries.addIndustry(industryName);
            if (manageIndustries.getSuccesful())
                txtIndustryName.setText("");
            labelMessage.setText(manageIndustries.getMessage());
        }
        catch (Exception ex)
        {
           btnRetry.setVisible(true);
           labelConnectionError.setVisible(true);
           btnAddIndustry.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_btnAddIndustryActionPerformed

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));   
        AddIndustry addIndustry = new AddIndustry(); // creates a new window identiacal to the current window
        dispose(); // disposes of the old window
        addIndustry.setVisible(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRetryActionPerformed

    private void txtIndustryNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIndustryNameKeyReleased
        // TODO add your handling code here:
        int length = txtIndustryName.getText().length();
        if (length > 35)
        {
            labelValidationMessage.setForeground(new java.awt.Color(204, 0, 0));
            labelValidationMessage.setText("Industry name too long (35 chars max)");
            labelValidationMessage.setVisible(true);
            btnAddIndustry.setEnabled(false);
        }
        else if (length < 2)
        {
            labelValidationMessage.setForeground(new java.awt.Color(204, 0, 0));
            labelValidationMessage.setText("Industry name too short");
            labelValidationMessage.setVisible(true);
            btnAddIndustry.setEnabled(false);
        }
        else
        {
            String industryEntered = txtIndustryName.getText();
            try
            {
                industries = new Industries();
                if(industries.checkIfIndustryExists(industryEntered) == false)
                {
                    labelValidationMessage.setForeground(new java.awt.Color(204, 0, 0));
                    labelValidationMessage.setText("Industry already exists");
                    labelValidationMessage.setVisible(true);
                    btnAddIndustry.setEnabled(false);
                }
                else
                {
                    labelValidationMessage.setForeground(new java.awt.Color(0, 204, 51));
                    labelValidationMessage.setText("Industry Name Valid");
                    labelValidationMessage.setVisible(true);
                    btnAddIndustry.setEnabled(true);
                }
            }
            catch(Exception ex)
            {
                
            }
        }
    }//GEN-LAST:event_txtIndustryNameKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddIndustry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddIndustry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddIndustry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddIndustry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddIndustry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIndustry;
    private javax.swing.JButton btnRetry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConnectionError;
    private javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelTitleText;
    private javax.swing.JLabel labelValidationMessage;
    public javax.swing.JTextField txtIndustryName;
    // End of variables declaration//GEN-END:variables
}
