

package Pages.Remove;

import AppFunctionality.Careers2Courses;
import AppFunctionality.Courses;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Ewald
 */
public class RemoveCourseOutcome extends javax.swing.JFrame {
    
    Courses courses;
    Careers2Courses c2c;
    
    ResultSet coursesRS;
    ResultSet c2cRS;

    /**
     * Creates new form RemoveCourseOutcome
     */
    public RemoveCourseOutcome() {
        initComponents();
        labelCourseOutcome.setEnabled(false);
        comboCourseOutcome.setEnabled(false);
        comboCourseOutcome.removeAllItems();
        comboCourseOutcome.addItem("- Select -");
        btnDelete.setEnabled(false);
        labelMessage.setVisible(false);
        labelRefreshMessage.setVisible(false);
        
        try
        {
            comboCourseName.removeAllItems();
            comboCourseName.addItem("- Select -");
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourseName.addItem(courseName);
            }
        }
        catch(Exception ex)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        comboCourseName = new javax.swing.JComboBox();
        labelCourseOutcome = new javax.swing.JLabel();
        comboCourseOutcome = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        btnRefreshList = new javax.swing.JButton();
        labelRefreshMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Course Outcome");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Remove Course Outcome");

        labelCourseName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCourseName.setForeground(new java.awt.Color(255, 255, 255));
        labelCourseName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCourseName.setText("Course Name:");

        comboCourseName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseNameActionPerformed(evt);
            }
        });

        labelCourseOutcome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCourseOutcome.setForeground(new java.awt.Color(255, 255, 255));
        labelCourseOutcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCourseOutcome.setText("Course Outcome:");

        comboCourseOutcome.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCourseOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseOutcomeActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("Message");
        labelMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMessageMouseClicked(evt);
            }
        });

        btnRefreshList.setText("Refresh List");
        btnRefreshList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshListActionPerformed(evt);
            }
        });

        labelRefreshMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelRefreshMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelRefreshMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRefreshMessage.setText("Lists have been Refreshed (click to hide)");
        labelRefreshMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRefreshMessageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCourseOutcome)
                            .addComponent(labelCourseName))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboCourseName, 0, 363, Short.MAX_VALUE)
                            .addComponent(comboCourseOutcome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelRefreshMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefreshList)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboCourseName, comboCourseOutcome});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseName)
                    .addComponent(comboCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefreshList))
                .addGap(16, 16, 16)
                .addComponent(labelRefreshMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseOutcome)
                    .addComponent(comboCourseOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelMessage)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboCourseName, comboCourseOutcome});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseNameActionPerformed
        // TODO add your handling code here:
        int index = comboCourseName.getSelectedIndex();
        comboCourseOutcome.removeAllItems();
        comboCourseOutcome.addItem("- Select -");
        if(index > 0)
        {
            String courseChosen = (String) comboCourseName.getSelectedItem();
            try
            {
                c2c = new Careers2Courses();
                c2cRS = c2c.listCareerOutcomeByCourse(courseChosen);
                while(c2cRS.next())
                {
                    String Outcome = c2cRS.getString("careerName");
                    comboCourseOutcome.addItem(Outcome);
                }
                labelCourseName.setEnabled(false);
                labelCourseOutcome.setEnabled(true);
                comboCourseOutcome.setEnabled(true);
            }
            catch(Exception ex)
            {
                
            }
        }
        else
        {
            labelCourseName.setEnabled(true);
            labelCourseOutcome.setEnabled(false);
            comboCourseOutcome.setEnabled(false);
            btnDelete.setEnabled(false);
            labelMessage.setVisible(false);
        }
    }//GEN-LAST:event_comboCourseNameActionPerformed

    private void comboCourseOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseOutcomeActionPerformed
        // TODO add your handling code here:
        int index = comboCourseOutcome.getSelectedIndex();
        if(index > 0)
        {
            labelCourseOutcome.setEnabled(false);
            btnDelete.setEnabled(true);
        }
        else
        {
            btnDelete.setEnabled(false);
            labelMessage.setVisible(false);
            labelCourseOutcome.setEnabled(true);
        }
    }//GEN-LAST:event_comboCourseOutcomeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String outcome = (String) comboCourseOutcome.getSelectedItem();
        String courseName = (String) comboCourseName.getSelectedItem();
        int prompt = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete '" + outcome + "' as \n"
                + "a possible job outcome for " + courseName + "?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (prompt == JOptionPane.YES_OPTION)
        {
            try
            {
              c2c = new Careers2Courses();
              c2c.removeCareerOutcome(courseName, outcome);
               labelMessage.setForeground(new java.awt.Color(255, 255, 255));
              labelMessage.setText("'" + outcome + "' has been removed as a possible job outcome for '" + courseName + "'");
              labelMessage.setVisible(true);
            }
            catch(Exception ex)
            {
               labelMessage.setForeground(new java.awt.Color(204, 0, 0));  
               labelMessage.setText("Error: Please check you connection");
               labelMessage.setVisible(true);
            }
        }
         
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void labelMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMessageMouseClicked
        // TODO add your handling code here:
        labelMessage.setVisible(false);
    }//GEN-LAST:event_labelMessageMouseClicked

    private void btnRefreshListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshListActionPerformed
        // TODO add your handling code here:
        labelCourseOutcome.setEnabled(false);
        comboCourseOutcome.setEnabled(false);
        comboCourseOutcome.removeAllItems();
        comboCourseOutcome.addItem("- Select -");
        btnDelete.setEnabled(false);
        labelMessage.setVisible(false);
        
        try
        {
            comboCourseName.removeAllItems();
            comboCourseName.addItem("- Select -");
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourseName.addItem(courseName);
            }
            labelRefreshMessage.setForeground(new java.awt.Color(255, 255, 255));
            labelRefreshMessage.setText("Lists have been refreshed (click to hide)");
            labelRefreshMessage.setVisible(true);
        }
        catch(Exception ex)
        {
            labelRefreshMessage.setForeground(new java.awt.Color(204, 0, 0));
            labelRefreshMessage.setText("Error: Unable to connect to the database");
            labelRefreshMessage.setVisible(true);
        }
    }//GEN-LAST:event_btnRefreshListActionPerformed

    private void labelRefreshMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRefreshMessageMouseClicked
        // TODO add your handling code here:
        labelRefreshMessage.setVisible(false);
    }//GEN-LAST:event_labelRefreshMessageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveCourseOutcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveCourseOutcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveCourseOutcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveCourseOutcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveCourseOutcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefreshList;
    public javax.swing.JComboBox comboCourseName;
    public javax.swing.JComboBox comboCourseOutcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labelCourseName;
    public javax.swing.JLabel labelCourseOutcome;
    public javax.swing.JLabel labelMessage;
    public javax.swing.JLabel labelRefreshMessage;
    // End of variables declaration//GEN-END:variables
}
