

package Pages.Remove;

import AppFunctionality.Courses;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Ewald
 */
public class RemoveCourse extends javax.swing.JFrame {

    Courses courses;
    
    ResultSet coursesRS;
    /**
     * Creates new form RemoveCourse
     */
    public RemoveCourse() {
        initComponents();
        labelMessage.setVisible(false);
        btnDelete.setEnabled(false); 
        labelRefreshMessage.setVisible(false);
        
        try
        {
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            comboCourseName.removeAllItems();
            comboCourseName.addItem("- Select -");
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourseName.addItem(courseName);
            }
        }
        catch(Exception ex)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        comboCourseName = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        labelRefreshMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Course");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Remove Course");

        labelCourseName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCourseName.setForeground(new java.awt.Color(255, 255, 255));
        labelCourseName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCourseName.setText("Course:");

        comboCourseName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCourseNameActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMessage.setText("Message");

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        labelRefreshMessage.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelRefreshMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelRefreshMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRefreshMessage.setText("The list has been refreshed");
        labelRefreshMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRefreshMessageMouseClicked(evt);
            }
        });
        labelRefreshMessage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                labelRefreshMessageKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelCourseName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh))
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMessage)
                            .addComponent(labelRefreshMessage))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCourseName)
                    .addComponent(btnRefresh))
                .addGap(13, 13, 13)
                .addComponent(labelRefreshMessage)
                .addGap(18, 18, 18)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelMessage)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String courseName = (String)comboCourseName.getSelectedItem();
        
        int prompt = JOptionPane.showConfirmDialog(null, "Deleting '" + courseName + "' will \n"
                + "also delete all career outcomes linked to the course \n\n Do you want to continue?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (prompt == JOptionPane.YES_OPTION)
        {
            try
            {
                courses = new Courses();
                courses.removeCourse(courseName);
                labelMessage.setForeground(new java.awt.Color(255, 255, 255));
                labelMessage.setText("'" + courseName + "' has been deleted.");
                labelMessage.setVisible(true);
            }
            catch(Exception ex)
            {
                labelMessage.setForeground(new java.awt.Color(204, 0, 0));
                labelMessage.setText("Error: Unable to connect to the database");
                labelMessage.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboCourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCourseNameActionPerformed
        // TODO add your handling code here:
        int index = comboCourseName.getSelectedIndex();
        if (index > 0)
            btnDelete.setEnabled(true);
        else
            btnDelete.setEnabled(false);
    }//GEN-LAST:event_comboCourseNameActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        labelMessage.setVisible(false);
        btnDelete.setEnabled(false);
        labelRefreshMessage.setVisible(false);
        
        try
        {
            courses = new Courses();
            coursesRS = courses.listAllCourses();
            comboCourseName.removeAllItems();
            comboCourseName.addItem("- Select -");
            while(coursesRS.next())
            {
                String courseName = coursesRS.getString("courseName");
                comboCourseName.addItem(courseName);
            }
            labelMessage.setForeground(new java.awt.Color(255, 255, 255));
            labelRefreshMessage.setText("The list has been refreshed (click to hide)");
            labelRefreshMessage.setVisible(true);
        }
        catch(Exception ex)
        {
            labelRefreshMessage.setForeground(new java.awt.Color(204, 0, 0));
            labelRefreshMessage.setText("Error connecting to the database.");
            labelRefreshMessage.setVisible(true);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void labelRefreshMessageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_labelRefreshMessageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_labelRefreshMessageKeyPressed

    private void labelRefreshMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRefreshMessageMouseClicked
        // TODO add your handling code here:
        labelRefreshMessage.setVisible(false);
    }//GEN-LAST:event_labelRefreshMessageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    public javax.swing.JComboBox comboCourseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCourseName;
    public javax.swing.JLabel labelMessage;
    private javax.swing.JLabel labelRefreshMessage;
    // End of variables declaration//GEN-END:variables
}
