package Pages.Remove;
import AppFunctionality.Disciplines;
import AppFunctionality.Industries;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Eunice Yeh
 */
public class RemoveDiscipline extends javax.swing.JFrame {
    Industries industries;
    Disciplines disciplines;
        
    ResultSet industriesRS;
    ResultSet disciplinesRS;
    /**
     * Creates new form RemoveDiscipline
     */
    public RemoveDiscipline() {
        initComponents();
        labelMessage.setText("");
        labelConnectionError.setVisible(false);
        btnRetry.setVisible(false);
      
        try
        {
            industries = new Industries();
            industriesRS = industries.listAllIndustries();
            comboIndustry.removeAllItems();
            comboIndustry.addItem("- Select -");
            while (industriesRS.next())
            {
                String industryName = industriesRS.getString("industryName");
                comboIndustry.addItem(industryName);
            }
        }
        catch(Exception ex)
        {
           btnRetry.setVisible(true);
           labelConnectionError.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboIndustry = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        comboDiscipline = new javax.swing.JComboBox();
        btnRemove = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        labelConnectionError = new javax.swing.JLabel();
        btnRetry = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Discipline");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Remove discipline");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Industry");

        comboIndustry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboIndustryActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Discipline");

        comboDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDisciplineActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnRefresh.setBorder(null);
        btnRefresh.setBorderPainted(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setFocusPainted(false);
        btnRefresh.setPreferredSize(new java.awt.Dimension(45, 23));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMessage.setText("This label  is not displayed by default");

        labelConnectionError.setForeground(new java.awt.Color(255, 255, 255));
        labelConnectionError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConnectionError.setText("Error: Unable to connect to database, please check your connection");

        btnRetry.setText("Retry");
        btnRetry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(labelConnectionError))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(btnRetry, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRemove)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboIndustry, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(comboDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove)
                .addGap(25, 25, 25)
                .addComponent(labelMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelConnectionError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRetry)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetryActionPerformed
        // TODO add your handling code here:
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        RemoveDiscipline removeDiscipline = new RemoveDiscipline(); // creates a new window identiacal to the current window
        dispose(); // disposes of the old window
        removeDiscipline.setVisible(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_btnRetryActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        int index = comboIndustry.getSelectedIndex();
        if (index > 0)
        {
        String industryChosen = (String) comboIndustry.getSelectedItem();
        comboDiscipline.removeAllItems();
        comboDiscipline.addItem("- Select -");
            try
            {
                industries = new Industries();
                int industryID = industries.getIndustryIDByName(industryChosen);
                disciplines = new Disciplines();
                disciplinesRS = disciplines.listDisciplinesByIndustryID(industryID);
                while(disciplinesRS.next())
                {
                    String disciplineName = disciplinesRS.getString("disciplineName");
                    comboDiscipline.addItem(disciplineName);
                    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                }
                comboDiscipline.setEnabled(true);
                           }
            catch(Exception ex)
            {
                setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
                comboIndustry.setEnabled(false);
                comboDiscipline.setEnabled (false);
                btnRetry.setVisible(true);
                labelConnectionError.setVisible(true);  
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            }
        } else{
        comboDiscipline.setEnabled(false);
        btnRemove.setEnabled(false);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void comboIndustryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboIndustryActionPerformed
        // TODO add your handling code here:
        int index = comboIndustry.getSelectedIndex();
      
        if (index > 0)
        {
            String industryChosen = (String) comboIndustry.getSelectedItem();
            comboDiscipline.removeAllItems();
            comboDiscipline.addItem("- Select -");
            try
            {
                industries = new Industries();
                int industryID = industries.getIndustryIDByName(industryChosen);
                disciplines = new Disciplines();
                disciplinesRS = disciplines.listDisciplinesByIndustryID(industryID);
                while(disciplinesRS.next())
                {
                    String disciplineName = disciplinesRS.getString("disciplineName");
                    comboDiscipline.addItem(disciplineName);
                }
                comboDiscipline.setEnabled(true);
                           }
            catch(Exception ex)
            {
                btnRetry.setVisible(true);
                labelConnectionError.setVisible(true);
            }
        } else{
        comboDiscipline.setEnabled(false);
        btnRemove.setEnabled(false);
        }
    }//GEN-LAST:event_comboIndustryActionPerformed

    private void comboDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDisciplineActionPerformed
        // TODO add your handling code here:
        int index = comboDiscipline.getSelectedIndex();
      
        if (index > 0)
        {
            btnRemove.setEnabled(true);
        }
        else{
            btnRemove.setEnabled(false);
        }
        
    }//GEN-LAST:event_comboDisciplineActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        String disciplineChosen = (String) comboDiscipline.getSelectedItem();
        int index = comboDiscipline.getSelectedIndex();
        
        //Popup dialog box
        if (JOptionPane.showConfirmDialog(null, "You are about to delete " + disciplineChosen + " and all its subsequent information."+"\n"
                                            + "Do you wish to continue?",
                                               "Confirmation", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            try
            {  // yes option
                disciplines = new Disciplines();
                int disciplineID = disciplines.getDisciplineIDByName(disciplineChosen);
                disciplines.removeDiscipline(disciplineID);
                labelMessage.setText("'" + disciplineChosen + "' has been removed from the database.");
                labelMessage.setVisible(true);
            }
            catch(Exception ex)
            {
                    labelMessage.setText("Error: Something went wrong.");
            }
       
        } else {
            // no option
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveDiscipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveDiscipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveDiscipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveDiscipline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveDiscipline().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRetry;
    private javax.swing.JComboBox comboDiscipline;
    private javax.swing.JComboBox comboIndustry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelConnectionError;
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables
}
