
package Pages.Remove;

import AppFunctionality.Careers;
import AppFunctionality.Disciplines;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin Ewald
 */
public class RemoveCareer extends javax.swing.JFrame {

    Disciplines disciplines;
    Careers careers;
    
    ResultSet disciplinesRS;
    ResultSet careersRS;
    /**
     * Creates new form RemoveCareer
     */
    public RemoveCareer() {
        initComponents();
        comboDiscipline.removeAllItems();
        comboDiscipline.addItem("- Select -");
        comboCareer.removeAllItems();
        comboCareer.addItem("- Select -");
        
        labelCareer.setEnabled(false);
        comboCareer.setEnabled(false);
        btnDelete.setEnabled(false);
        labelMessage.setVisible(false);
       
        try
        {
            disciplines = new Disciplines();
            disciplinesRS = disciplines.listAllDisciplines();
            while(disciplinesRS.next())
            {
                String disciplineName = disciplinesRS.getString("disciplineName");
                comboDiscipline.addItem(disciplineName);
            }
        }
        catch(Exception ex)
        {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelDiscipline = new javax.swing.JLabel();
        labelCareer = new javax.swing.JLabel();
        comboDiscipline = new javax.swing.JComboBox();
        comboCareer = new javax.swing.JComboBox();
        btnDelete = new javax.swing.JButton();
        labelMessage = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Career");

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Remove Career");

        labelDiscipline.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDiscipline.setForeground(new java.awt.Color(255, 255, 255));
        labelDiscipline.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelDiscipline.setText("Discipline:");

        labelCareer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelCareer.setForeground(new java.awt.Color(255, 255, 255));
        labelCareer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCareer.setText("Career:");

        comboDiscipline.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDisciplineActionPerformed(evt);
            }
        });

        comboCareer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCareerActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Career");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        labelMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelMessage.setForeground(new java.awt.Color(255, 255, 255));
        labelMessage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelMessage.setText("jLabel2");
        labelMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelMessageMouseClicked(evt);
            }
        });

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDiscipline)
                            .addComponent(labelCareer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comboDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelMessage)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboCareer, comboDiscipline});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiscipline)
                    .addComponent(comboDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCareer))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMessage))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {comboCareer, comboDiscipline});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDisciplineActionPerformed
        // TODO add your handling code here:
        int index = comboDiscipline.getSelectedIndex();
        comboCareer.removeAllItems();
        comboCareer.addItem("- Select -");
        if (index > 0)
        {
            String disciplineChosen = (String) comboDiscipline.getSelectedItem();
            try
            {   
                disciplines = new Disciplines();
                int disciplineID = disciplines.getDisciplineIDByName(disciplineChosen);
                careers = new Careers();
                careersRS = careers.listCareers(disciplineID);
                while (careersRS.next())
                {
                    String careerName = careersRS.getString("careerName");
                    comboCareer.addItem(careerName);
                }
                labelDiscipline.setEnabled(false);
                labelCareer.setEnabled(true);
                comboCareer.setEnabled(true);
                btnDelete.setEnabled(false);
                labelMessage.setVisible(false);
            }
            catch(Exception ex){}
        }
        else
        {
            labelDiscipline.setEnabled(true);
            comboCareer.setEnabled(false);
            labelCareer.setEnabled(false);
            btnDelete.setEnabled(false);
            labelMessage.setVisible(false);
        }
    }//GEN-LAST:event_comboDisciplineActionPerformed

    private void comboCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCareerActionPerformed
        // TODO add your handling code here:
        int index = comboCareer.getSelectedIndex();
        if (index > 0)
        {
            btnDelete.setEnabled(true);
            labelMessage.setVisible(false);
            labelCareer.setEnabled(false);
        }
        else
        {
            btnDelete.setEnabled(false);
            labelMessage.setVisible(false);
            labelCareer.setEnabled(true);
        }
    }//GEN-LAST:event_comboCareerActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String careerName = (String) comboCareer.getSelectedItem();
        
        int prompt = JOptionPane.showConfirmDialog(null, "Deleting '" + careerName + "' will \n"
                + "also delete all data linked to this career. \n\n Do you want to continue?", "Confirm",
        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        
        if (prompt == JOptionPane.YES_OPTION)
        {
            try
            {
                careers = new Careers();
                careers.removeCareer(careerName);
                labelMessage.setText(careerName + " has been successfully deleted");
                labelMessage.setVisible(true);
            }
            catch(Exception ex)
            {

            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void labelMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMessageMouseClicked
        // TODO add your handling code here:
        labelMessage.setVisible(false);
    }//GEN-LAST:event_labelMessageMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        comboDiscipline.removeAllItems();
        comboDiscipline.addItem("- Select -");
        comboCareer.removeAllItems();
        comboCareer.addItem("- Select -");
        
        labelCareer.setEnabled(false);
        comboCareer.setEnabled(false);
        btnDelete.setEnabled(false);
        labelMessage.setVisible(false);
       
        try
        {
            disciplines = new Disciplines();
            disciplinesRS = disciplines.listAllDisciplines();
            while(disciplinesRS.next())
            {
                String disciplineName = disciplinesRS.getString("disciplineName");
                comboDiscipline.addItem(disciplineName);
            }
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveCareer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveCareer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveCareer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveCareer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveCareer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox comboCareer;
    private javax.swing.JComboBox comboDiscipline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCareer;
    private javax.swing.JLabel labelDiscipline;
    private javax.swing.JLabel labelMessage;
    // End of variables declaration//GEN-END:variables
}
